<a href="https://colab.research.google.com/github/Mohanaprema/ML-Projects-samples/blob/main/day_01_case_study_class_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1) Data collection from source system.
import pandas as pd

customer_df = pd.read_csv('Mall_Customers.csv')

In [ ]:
# 2) Data Selection ( SELET Statement )

# SQL Query : SELECT * FROM customer_df

# Pandas Equvament:
customer_df

     CustomerID   Genre  Age  Annual_Income_K_Dollars  Spending_Score_1_to_100
0             1    Male   19                       15                       39
1             2    Male   21                       15                       81
2             3  Female   20                       16                        6
3             4  Female   23                       16                       77
4             5  Female   31                       17                       40
..          ...     ...  ...                      ...                      ...
195         196  Female   35                      120                       79
196         197  Female   45                      126                       28
197         198    Male   32                      126                       74
198         199    Male   32                      137                       18
199         200    Male   30                      137                       83

[200 rows x 5 columns]

In [ ]:
# 3) Data Selection only with limited rows (LIMIT Statement)

# SQL Query mySQL : SELECT * FROM customer_df LIMIT 10 ;

# SQL Query Mssql : SELECT TOP 10 * FROM customer_df;

# Pandas Equvament:
customer_df.head(10)

   CustomerID   Genre  Age  Annual_Income_K_Dollars  Spending_Score_1_to_100
0           1    Male   19                       15                       39
1           2    Male   21                       15                       81
2           3  Female   20                       16                        6
3           4  Female   23                       16                       77
4           5  Female   31                       17                       40
5           6  Female   22                       17                       76
6           7  Female   35                       18                        6
7           8  Female   23                       18                       94
8           9    Male   64                       19                        3
9          10  Female   30                       19                       72

In [ ]:
# 4) Data Selection with 10 rows of several attributes

# SQL Query : SELECT genre, Age FROM Customer_df LIMIT 10;

# Pandas Equvament:
customer_df[['Genre','Age']].head(10)

    Genre  Age
0    Male   19
1    Male   21
2  Female   20
3  Female   23
4  Female   31
5  Female   22
6  Female   35
7  Female   23
8    Male   64
9  Female   30

In [ ]:
# 5) Data Selection with Filter condition (SELECT .... WHERE )

# SQL Query : SELECT CustomerID,Genre FROM Customer_df WHERE Annual_Income_K_Dollars = 16;

# Pandas Equvament:
customer_df[customer_df['Annual_Income_K_Dollars'] == 16][['CustomerID','Genre']]

   CustomerID   Genre
2           3  Female
3           4  Female

In [ ]:
# 6) Data Selection with mulitple filter condtitions ( SELECT WHERE(mulitple condition , all columns))

# SQL Query : SELECT * FROM Customer_df WHERE Annual_Income_K_Dollars >= 100 AND Genre ='Female';

# Pandas Equvament:

customer_df[(customer_df['Annual_Income_K_Dollars'] >= 100) & (customer_df['Genre'] == 'Female')]

     CustomerID   Genre  Age  Annual_Income_K_Dollars  Spending_Score_1_to_100
186         187  Female   54                      101                       24
188         189  Female   41                      103                       17
189         190  Female   36                      103                       85
190         191  Female   34                      103                       23
191         192  Female   32                      103                       69
193         194  Female   38                      113                       91
194         195  Female   47                      120                       16
195         196  Female   35                      120                       79
196         197  Female   45                      126                       28

In [ ]:
# 7) Data Selection with mulitple filter condtitions ( SELECT WHERE(mulitple condition , specific columns))

# SQL Query :  # SQL Query : SELECT Genre, Age, CustomerID FROM Customer_df WHERE Annual_Income_K_Dollars >= 100 AND Genre ='Female';

# Pandas Equvament:

customer_df[(customer_df['Annual_Income_K_Dollars'] >= 100) & (customer_df['Genre'] == 'Female')] [['Genre','Age','CustomerID']]

      Genre  Age  CustomerID
186  Female   54         187
188  Female   41         189
189  Female   36         190
190  Female   34         191
191  Female   32         192
193  Female   38         194
194  Female   47         195
195  Female   35         196
196  Female   45         197

In [ ]:
customer_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CustomerID               200 non-null    int64
 1   Genre                    200 non-null    str
 2   Age                      200 non-null    int64
 3   Annual_Income_K_Dollars  200 non-null    int64
 4   Spending_Score_1_to_100  200 non-null    int64
dtypes: int64(4), str(1)
memory usage: 7.9 KB

In [ ]:
# 8) Summary Level Data (Aggregate level info)(avg, max, min)

# SQL Query :  SELECT AVG(Age), MAX(Age), MIN(Age) FROM Customer_df; alwasy have 1 record has output.

# Pandas Equvament:
# Normal way
customer_df['Age'].mean(), customer_df['Age'].max(), customer_df['Age'].min()

# Best Method
customer_df.agg({'Age':['mean','max','min','sum', 'count']})

           Age
mean     38.85
max      70.00
min      18.00
sum    7770.00
count   200.00

In [ ]:
# 9) Data Selection with Unique value for the selected columns

# SQL Query : SELECT DISTINCT Genre FROM Customer_df;

# Pandas Equvament:

customer_df['Genre'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [ ]:
# 10) Data Selection with unique value for mulitple columns

# SQL Query : SELECT DISTINCT Genre,Annual_Income_K_Dollars FROM customer_df;

# Pandas Equvament:
customer_df[['Genre','Annual_Income_K_Dollars']].drop_duplicates()

      Genre  Annual_Income_K_Dollars
0      Male                       15
2    Female                       16
4    Female                       17
6    Female                       18
8      Male                       19
..      ...                      ...
193  Female                      113
194  Female                      120
196  Female                      126
197    Male                      126
198    Male                      137

[103 rows x 2 columns]

In [ ]:
# 11) Data Selection with unique value for mulitple columns in one vector (single column)

# SQL Query :

'''
SELECT DISTINCT Spending_Score_1_to_100 FROM customer_Df
UNION
SELECT DISTINCT Annual_Income_K_Dollars FROM customer_Df
'''
# Pandas Equvament:
import numpy as np

np.unique(customer_df[['Spending_Score_1_to_100','Annual_Income_K_Dollars']])

array([  1,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        81,  82,  83,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  97,  98,  99, 101, 103, 113, 120, 126, 137])

In [ ]:
# 12) Data Seletion with ordering the output (Ascending order)

# SQL Query : SELECT * FROM customer_df WHERE genre = 'Female' ORDER BY Spending_Score_1_to_100 ASC;

# Pandas Equvament:

customer_df[customer_df['Genre'] =='Female'].sort_values(by='Spending_Score_1_to_100',ascending=True).reset_index()

,index,CustomerID,Genre,Age,Annual_Income_K_Dollars,Spending_Score_1_to_100
0,22,23,Female,46,25,5
1,140,141,Female,57,75,5
2,6,7,Female,35,18,6
3,2,3,Female,20,16,6
4,136,137,Female,44,73,7
...,...,...,...,...,...,...
107,163,164,Female,31,81,93
108,7,8,Female,23,18,94
109,167,168,Female,33,86,95
110,19,20,Female,35,23,98
111,11,12,Female,35,19,99

In [ ]:
# 13) Data Seletion with ordering the output (Desceding order)

# SQL Query : SELECT * FROM customer_df WHERE genre = 'Female' ORDER BY Spending_Score_1_to_100 DESC;

# Pandas Equvament: customer_df
customer_df[['Genre'] =='Female'].sort_values(by='Spending_Score_1_to_100',ascending=False).reset_index()

,index,CustomerID,Genre,Age,Annual_Income_K_Dollars,Spending_Score_1_to_100
0,11,12,Female,35,19,99
1,19,20,Female,35,23,98
2,167,168,Female,33,86,95
3,7,8,Female,23,18,94
4,163,164,Female,31,81,93
...,...,...,...,...,...,...
107,136,137,Female,44,73,7
108,2,3,Female,20,16,6
109,6,7,Female,35,18,6
110,22,23,Female,46,25,5
111,140,141,Female,57,75,5

In [ ]:
customer_df

     CustomerID   Genre  Age  Annual_Income_K_Dollars  Spending_Score_1_to_100
0             1    Male   19                       15                       39
1             2    Male   21                       15                       81
2             3  Female   20                       16                        6
3             4  Female   23                       16                       77
4             5  Female   31                       17                       40
..          ...     ...  ...                      ...                      ...
195         196  Female   35                      120                       79
196         197  Female   45                      126                       28
197         198    Male   32                      126                       74
198         199    Male   32                      137                       18
199         200    Male   30                      137                       83

[200 rows x 5 columns]

In [ ]:
customer_df

     CustomerID   Genre  Age  Annual_Income_K_Dollars  Spending_Score_1_to_100
0             1    Male   19                       15                       39
1             2    Male   21                       15                       81
2             3  Female   20                       16                        6
3             4  Female   23                       16                       77
4             5  Female   31                       17                       40
..          ...     ...  ...                      ...                      ...
195         196  Female   35                      120                       79
196         197  Female   45                      126                       28
197         198    Male   32                      126                       74
198         199    Male   32                      137                       18
199         200    Male   30                      137                       83

[200 rows x 5 columns]

In [ ]:
customer_df.sort_values(by='Spending_Score_1_to_100',ascending=False,inplace=True)
customer_df.reset_index(inplace=True)

In [ ]:
customer_df.head()

,index,CustomerID,Genre,Age,Annual_Income_K_Dollars,Spending_Score_1_to_100
0,11,12,Female,35,19,99
1,19,20,Female,35,23,98
2,145,146,Male,28,77,97
3,185,186,Male,30,99,97
4,167,168,Female,33,86,95